# Generated by Django 4.2.7 on 2023-12-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=128)),
                ('country_brand', models.CharField(max_length=256)),
                ('description_brand', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
